"""Configuration values for the Motion-Aware Smart Surveillance System."""

VIDEO_PATH = "videos/video_project.mp4"
OUTPUT_PATH = "outputs/output_video.mp4"

MIN_CONTOUR_AREA = 1100
MIN_BOX_WIDTH = 18
MIN_BOX_HEIGHT = 25
BOX_MERGE_MARGIN = 8

LARGE_OBJECT_AREA_RATIO = 0.018
PERSON_MAX_AREA_RATIO = 0.012
PERSON_MAX_ASPECT_RATIO = 0.95
PERSON_STRICT_ASPECT_RATIO = 0.75
PERSON_LARGE_AREA_RATIO = 0.08
CAR_MIN_AREA_RATIO = 0.006
CAR_MIN_WIDTH_RATIO = 0.060
CAR_MIN_HEIGHT_RATIO = 0.035
CAR_MIN_SPEED_FOR_SHAPE_ONLY = 4.0
VEHICLE_ASPECT_RATIO = 1.35
VEHICLE_MIN_LINES = 6
VEHICLE_MIN_CIRCLES = 2
FAST_OBJECT_SPEED = 6.0
DISPLAY_MIN_MOTION_RATIO = 0.08
DISPLAY_MIN_SPEED = 1.5
STATIC_WIDE_OBJECT_MAX_SPEED = 3.0
STATIC_WIDE_OBJECT_MIN_ASPECT = 1.15
STATIC_VEHICLE_IGNORE_REGIONS = [
    (400, 320, 920, 610),
]
STATIC_REGION_OVERLAP_THRESHOLD = 0.20

COUNTING_LINE_Y = 540
MAX_DISTANCE = 120
MAX_MISSING_FRAMES = 20
CLASS_SCORE_DECAY = 0.85

CANNY_LOW = 50
CANNY_HIGH = 150
CANNY_AUTO_SIGMA = 0.33
HOUGH_MIN_LINE_LENGTH_RATIO = 0.22
HOUGH_MAX_LINE_GAP_RATIO = 0.05
CIRCLE_EDGE_SUPPORT_THRESHOLD = 0.12
MAX_DRAWN_HOUGH_LINES = 12
MAX_DRAWN_HOUGH_CIRCLES = 6

COUNTED_CLASSES = ["Person", "Car", "Moving Object"]
VEHICLE_CLASSES = ["Car"]

MOTION_RATIO_THRESHOLD = 0.02
SHOW_MOTION_MASK = False
SAVE_OUTPUT = True
